name: 测试签名
on:
  workflow_dispatch:  # 允许手动触发工作流
    inputs:
      buildType:
        description: 'Build type'
        required: true
        default: 'release'
        type: choice
        options:
          - debug
          - release
      versionSuffix:
        description: 'Optional suffix for version name'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
        
    - name: 准备签名密钥
      if: github.event.inputs.buildType == 'release'  # 仅在 release 构建时需要
      run: |
        # 解码密钥库
        echo "${{ secrets.RELEASE_KEYSTORE_BASE64 }}" | base64 -d > app/siowu.jks
        mkdir -p ~/.android
        if [ -f "app/siowu.jks" ]; then
          echo "签名文件恢复成功"
        else
          echo "错误：签名文件恢复失败"
          exit 1
        fi
        echo "storeFile=$(pwd)/siowu.jks" > ~/.android/debug.keystore.properties
        echo "storePassword=${{ secrets.RELEASE_STORE_PASSWORD }}" >> ~/.android/debug.keystore.properties
        echo "keyAlias=${{ secrets.RELEASE_KEY_ALIAS }}" >> ~/.android/debug.keystore.properties
        echo "keyPassword=${{ secrets.RELEASE_KEY_PASSWORD }}" >> ~/.android/debug.keystore.properties
      
